### ISSUE TITLE
Update to MegaParsec has broken Cabal install

### ISSUE THREAD

**Issue by EdNutting** [idris-lang/Idris-dev#4551]
Hi,

# Steps to Reproduce

Attempt a clean install of Idris using Cabal 2.4.0 with the latest package list.

# Expected Behavior

Idris should install cleanly without errors.

# Observed Behavior

When attempting to build package 67 of 115 : Idris.Parser.Stack the following error occurs:

```
src/Idris/Parser/Stack.hs:70:29: error:
    Not in scope: ‘P.errorPos’
    Module ‘Text.Megaparsec’ does not export ‘errorPos’.

src/Idris/Parser/Stack.hs:76:34: error:
    Not in scope: ‘P.parseErrorPretty'’
    Perhaps you meant one of these:
      ‘P.parseErrorPretty’ (imported from Text.Megaparsec),
      ‘P.parseErrorTextPretty’ (imported from Text.Megaparsec)
    Module ‘Text.Megaparsec’ does not export ‘parseErrorPretty'’.

src/Idris/Parser/Stack.hs:107:30: error:
    Not in scope: ‘P.getPosition’
    Module ‘Text.Megaparsec’ does not export ‘getPosition’.
```

# Expected fix

The Idris build config should be pinned to the correct version of MegaParsec (and/or any other packages that aren't pinned to working versions?)

Cheers,
Ed

**Comment by EdNutting** [comment]
Note that the update was released to Hackage yesterday (4th September)

**Comment by melted** [comment]
Thanks for the report, I’ll fix it after work.

**Comment by code5hot** [comment]
This doesn't seem to be fixed. After cabal update and updating other packages such as megaparsec, when I run "cabal install idris" I still get

src/Idris/Parser/Stack.hs:107:30: error:
    Not in scope: ‘P.getPosition’
    Module ‘Text.Megaparsec’ does not export ‘getPosition’.
cabal: Leaving directory '/tmp/cabal-tmp-20411/idris-1.3.0'
cabal: Error: some packages failed to install:
idris-1.3.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by ShuoLearner** [comment]
> This doesn't seem to be fixed. After cabal update and updating other packages such as megaparsec, when I run "cabal install idris" I still get
> 
> src/Idris/Parser/Stack.hs:107:30: error:
> Not in scope: ‘P.getPosition’
> Module ‘Text.Megaparsec’ does not export ‘getPosition’.
> cabal: Leaving directory '/tmp/cabal-tmp-20411/idris-1.3.0'
> cabal: Error: some packages failed to install:
> idris-1.3.0 failed during the building phase. The exception was:
> ExitFailure 1

===============================
I tried the following steps, and it worked on Ubuntu 18.04
(1) cabal install megaparsec-6.5.0
(2) ghc-pkg unregister --force megaparsec-7.0.1
(3) cabal install idirs

**Comment by melted** [comment]
It has been fixed on master, but that hasn’t been released yet.

**Comment by DestyNova** [comment]
Perhaps a note about this could be added to the install instructions? As a newcomer to Idris I was surprised to find that the installation instructions took a long time (due to installing many, many packages with cabal) and then failed.

**Comment by zmgsabstract** [comment]
I too had this problem on a fresh install, just coming to the language -- which is off-putting to new people.

**Comment by shri2016** [comment]
> > This doesn't seem to be fixed. After cabal update and updating other packages such as megaparsec, when I run "cabal install idris" I still get
> > src/Idris/Parser/Stack.hs:107:30: error:
> > Not in scope: ‘P.getPosition’
> > Module ‘Text.Megaparsec’ does not export ‘getPosition’.
> > cabal: Leaving directory '/tmp/cabal-tmp-20411/idris-1.3.0'
> > cabal: Error: some packages failed to install:
> > idris-1.3.0 failed during the building phase. The exception was:
> > ExitFailure 1
> 
> ===============================
> I tried the following steps, and it worked on Ubuntu 18.04
> (1) cabal install megaparsec-6.5.0
> (2) ghc-pkg unregister --force megaparsec-7.0.1
> (3) cabal install idris

This worked for me, thanks @ShuoLearner!
