### ISSUE TITLE
Linking fails on Win64 with 1.3

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris-dev#4463]
# Steps to Reproduce
src/Main.idr:
```
module Main

main : IO ()
main = putStrLn "Hello world"
```
test.ipkg:
```
package test

executable = test

main = Main

modules = Main

sourcedir = src
```
# Expected Behavior
Compiles on both 1.2 and 1.3.
# Observed Behavior
Compiles on 1.2, errors out on 1.3:
```
D:\temp\test>idris --build test.ipkg                                                                                                                                                                                                            
Entering directory `.\src'                                                                                                                                                                                                                      
Type checking .\Main.idr                                                                                                                                                                                                                        
D:\idris\./libs\rts/libidris_rts.a(idris_rts.o):idris_rts.c:(.text$printf+0x29): undefined reference to `__imp___acrt_iob_func'                                                                                                                 
D:\idris\./libs\rts/libidris_rts.a(idris_rts.o):idris_rts.c:(.text$idris_trace+0x2f): undefined reference to `__imp___acrt_iob_func'                                                                                                            
D:\idris\./libs\rts/libidris_rts.a(idris_rts.o):idris_rts.c:(.text$idris_castBitsStr+0xf0): undefined reference to `__imp___acrt_iob_func'                                                                                                      
D:\idris\./libs\rts/libidris_rts.a(idris_rts.o):idris_rts.c:(.text$idris_crash+0xf): undefined reference to `__imp___acrt_iob_func'                                                                                                             
D:\idris\./libs\rts/libidris_rts.a(idris_rts.o):idris_rts.c:(.text$idris_sendMessage+0x15f): undefined reference to `__imp___acrt_iob_func'                                                                                                     
D:\idris\./libs\rts/libidris_rts.a(idris_rts.o):idris_rts.c:(.text$idris_disableBuffering+0x8): more undefined references to `__imp___acrt_iob_func' follow                                                                                     
collect2.exe: error: ld returned 1 exit status                                                                                                                                                                                                  
FAILURE: "gcc" ["-O1","-foptimize-sibling-calls","-fwrapv","-fno-strict-overflow","-std=c99","-pipe","-fdata-sections","-ffunction-sections","-D_POSIX_C_SOURCE=200809L","-DHAS_PTHREAD","-DIDRIS_ENABLE_STATS","-I.","-Wl,-gc-sections","-Wl,--
stack,16777216","C:\\Users\\A80C4~1.GRY\\AppData\\Local\\Temp\\idris20132-0.c","-LD:\\idris\\./libs\\rts","-lidris_rts","-lpthread","-ID:\\idris\\./libs\\rts","-lm","-I.","-ID:\\idris\\./libs\\libs\\prelude","-ID:\\idris\\./libs\\libs\\base
","-ID:\\Niklas\\repo\\Idris-dev\\dist\\dist-sandbox-8527c5fc\\build\\idris\\./libs\\libs\\prelude","-ID:\\Niklas\\repo\\Idris-dev\\dist\\dist-sandbox-8527c5fc\\build\\idris\\./libs\\libs\\base","-I.","-ID:\\Niklas\\repo\\Idris-dev\\.cabal-
sandbox\\x86_64-windows-ghc-8.2.2\\idris-1.2.0\\libs\\prelude","-ID:\\Niklas\\repo\\Idris-dev\\.cabal-sandbox\\x86_64-windows-ghc-8.2.2\\idris-1.2.0\\libs\\base","-o","D:\\temp\\test\\test"]                                                  
```

I'm guessing I should tag @melted on this?

**Comment by melted** [comment]
I saw the posting on the mailing list. It's apparently mingw version skew between the bundled GCC and the one I built with. I'll package a new toolchain and update the binaries.

**Comment by clayrat** [comment]
Ah sorry, I've missed that post.

**Comment by melted** [comment]
It's good to have an issue.

**Comment by melted** [comment]
Ok, I have uploaded new versions where I have replaced the toolchain.

I must have forgotten to run my smoketest, I should add that to the release script.

**Comment by melted** [comment]
Thanks for the report!

**Comment by nedzadarek** [comment]
@melted It might be stupid question but where can I download the binaries? https://github.com/idris-lang/Idris-dev/wiki/Windows-Binaries is from 10 day ago.

**Comment by nedzadarek** [comment]
@melted It works. Thank you very much.
