### PR TITLE
Make Setup.hs build with GHC 8.2

### LINKED ISSUE #3956: Cabal 2.0.0.2 incompatibility
The build failure is 
```
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/idris/1.0.1 -f FFI -f release
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/opt/libffi/lib'
clang: warning: argument unused during compilation: '-L/usr/local/lib'
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Resolving dependencies...
Notice: installing into a sandbox located at
/private/tmp/idris-20170801-1139-1ykhe4s/Idris-dev-1.0.1/.cabal-sandbox
Configuring idris-1.0.1...
Failed to install idris-1.0.1
Build log ( /private/tmp/idris-20170801-1139-1ykhe4s/Idris-dev-1.0.1/.cabal-sandbox/logs/idris-1.0.1.log ):
cabal: Entering directory '.'
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
idris-1.0.1 failed during the configure step. The exception was:
user error ('/usr/local/opt/ghc/bin/ghc' exited with an error:

dist/dist-sandbox-15a7f92e/setup/setup.hs:59:16: error:
• Data constructor not in scope: FlagName :: [Char] -> FlagName
• Perhaps you meant one of these:
variable ‘flagName’ (imported from Distribution.PackageDescription),
variable ‘mkFlagName’ (imported from Distribution.PackageDescription),
variable ‘unFlagName’ (imported from Distribution.PackageDescription)
|
59 | case lookup (FlagName "gmp") (S.configConfigurationsFlags flags) of
| ^^^^^^^^

dist/dist-sandbox-15a7f92e/setup/setup.hs:66:16: error:
• Data constructor not in scope: FlagName :: [Char] -> FlagName
• Perhaps you meant one of these:
variable ‘flagName’ (imported from Distribution.PackageDescription),
variable ‘mkFlagName’ (imported from Distribution.PackageDescription),
variable ‘unFlagName’ (imported from Distribution.PackageDescription)
|
66 | case lookup (FlagName "execonly") (S.configConfigurationsFlags flags) of
| ^^^^^^^^

dist/dist-sandbox-15a7f92e/setup/setup.hs:73:18: error:
• Data constructor not in scope: FlagName :: [Char] -> FlagName
• Perhaps you meant one of these:
variable ‘flagName’ (imported from Distribution.PackageDescription),
variable ‘mkFlagName’ (imported from Distribution.PackageDescription),
variable ‘unFlagName’ (imported from Distribution.PackageDescription)
|
73 | case lookup (FlagName "release") (S.configConfigurationsFlags flags) of
| ^^^^^^^^

dist/dist-sandbox-15a7f92e/setup/setup.hs:80:16: error:
• Data constructor not in scope: FlagName :: [Char] -> FlagName
• Perhaps you meant one of these:
variable ‘flagName’ (imported from Distribution.PackageDescription),
variable ‘mkFlagName’ (imported from Distribution.PackageDescription),
variable ‘unFlagName’ (imported from Distribution.PackageDescription)
|
80 | case lookup (FlagName "freestanding") (S.configConfigurationsFlags flags)
of
| ^^^^^^^^
)
```

Note the deprecations

> - Backwards incompatible change to 'FlagName' (#4062)
> - Backwards incompatible change to 'Version' (#3905)

here:
https://github.com/haskell/cabal/blob/2d3135722fa08294d3425b3f9333e124c1f48de1/Cabal/changelog#L59

(To get this far, you first need to add allow-newer for base,process,time,trifecta if you're using GHC 8.2.1)

### PR DESCRIPTION
**Pull request by RyanGlScott**
`Cabal-2.0` (which is bundled with GHC 8.2) changed its API quite a bit, so let's update `Setup.hs` accordingly. Fixes #3956 .

### CODE REVIEW

**Comment by melted** [comment]
The appveyor build didn't go well https://ci.appveyor.com/project/idrislang/idris-dev/build/1.0.1143

I think some more magic is needed for older GHCs, see hvrs comment on https://github.com/idris-lang/Idris-dev/issues/3956

**Comment by ahmadsalim** [comment]
Fixes #3956

**Comment by ahmadsalim** [comment]
I updated the PR description, so it will close the related issue automatically.

**Comment by melted** [comment]
some travis jobs timed out. But any failures here would have resulted in an early termination so it's all good.

**Comment by ilovezfs** [comment]
Thanks for the fix @RyanGlScott!
